#! /bin/bash
set -e
set -o pipefail


rscript="
library(devtools);
library(dplyr);
library(ggplot2);
library(ggpubr);
library(BiocManager);
sessionInfo()
"

r_package_version=$(Rscript -e "$rscript")
python_package_version=$(pip3 freeze)

echo `date`
echo "# R packages version"
echo '```'
echo "$r_package_version"
echo '```'

echo ""
echo ""
echo "# Python packages version"
echo '```'
echo "$python_package_version"
echo '```'




