#! /bin/bash
set -e
set -o pipefail



python_package_version=$(pip3 freeze)

echo `date`
echo "# R packages version"
echo '```'
echo "$r_package_version"
echo '```'

echo ""
echo ""
echo "# Python packages version"
echo '```'
echo "$python_package_version"
echo '```'




